LIGNE = 16
COLLONE = 16
GRILLE = 48
PANNEAU_LARGEUR = 300

SCREEN_WIDTH = GRILLE * COLLONE
SCREEN_HEIGHT = GRILLE * LIGNE
FPS = 60
NOMBRE_NIVEAU = 15

NIVEAU_VIE = 100
MONNAIE = 100

#CONSTANTE ENNEMIES
SPAWN_COOLDOWN = 400


#CONSTANTE TOUR
NIVEAU_MAX = 3
ACHETER_COUT = 50
RECOMPENSE_TUE = 5
AMELIORER_COUT = 30
DEGATS = 50

NIVEAU_FINI = 150